### ISSUE TITLE
Erro de digitação

### ISSUE THREAD

**Issue by glaucosoares** [ufpb-computacao/fundamentos-socio-historico-da-educacao-livro#12]
Versão do livro: Ed. v1.0.4
Página 6

Onde está escrito "... pelo também alemão Max Weber (1964-1920)..."

O período deveria ser Max Weber (1864-1920)

fonte: https://pt.wikipedia.org/wiki/Max_Weber

**Comment by edusantana** [comment]
Obrigado @glaucosoares 

É através de contribuições como as suas que poderemos melhorar ainda mais nosso material, obrigado!
